### ISSUE TITLE
Bulk Checkout errors

### ISSUE THREAD

**Issue by agates62** [bricelabelle/snipe-it-bulkedit#1]
Hello, 

First off thanks for all of this. Second, bulk update is working, but bulk checkin/out isn't working. I fill out the form and it just sits, so I'm guessing its hitting errors. Any troubleshoot thoughts?

**Comment by bricelabelle** [comment]
Hi @agates62, I'm sorry I missed this. I see you got checkout to work but not checkin. Did you ever get it figured out? Please follow my instructions on issue #2 for troubleshooting checkin/checkout.
